- type: job
  id: TypanBorg
  name: киборг синдиката
  description: job-description-borg
  playTimeTracker: JobBorgTypan
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hrs
  canBeAntag: false
  icon: JobIconTypanBorg
  supervisors: job-supervisors-typan-syndicate
  jobEntity: PlayerBorgSyndicateSaboteurBattery
  applyTraits: false
  access:
  - TypanArmory
  - TypanAtmospherics
  - TypanCargo
  - TypanCommand
  - TypanCommunicationsOfficer
  - TypanEngineering
  - TypanMaint
  - TypanMedical
  - TypanProtection
  - TypanResearchDirector
  - TypanScience
  - TypanService
  - TypanTechnicalOperationsSupervisor
  - TypanVault
  - TypanExternal
  - SyndicateAgent
  special:
  - !type:AddComponentSpecial
    components:
      - type: AntagImmune
      - type: NpcFactionMember
        factions:
        - Typan

- type: job
  id: TypanBorgMedic
  name: медкиборг синдиката
  description: job-description-borg
  playTimeTracker: JobBorgTypanMedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hrs
  canBeAntag: false
  icon: JobIconTypanBorg
  supervisors: job-supervisors-typan-syndicate
  jobEntity: PlayerBorgSyndicateMedicalBattery
  applyTraits: false
  access:
  - TypanArmory
  - TypanAtmospherics
  - TypanCargo
  - TypanCommand
  - TypanCommunicationsOfficer
  - TypanEngineering
  - TypanMaint
  - TypanMedical
  - TypanProtection
  - TypanResearchDirector
  - TypanScience
  - TypanService
  - TypanTechnicalOperationsSupervisor
  - TypanVault
  - TypanExternal
  - SyndicateAgent
  special:
  - !type:AddComponentSpecial
    components:
      - type: AntagImmune
      - type: NpcFactionMember
        factions:
        - Typan
